#ifndef MXFTOOLS_VERSION_H
#define MXFTOOLS_VERSION_H

#define MXFTOOLS_VERSION_MAJOR 1
#define MXFTOOLS_VERSION_MINOR 0
#define MXFTOOLS_VERSION_MICRO 0

#define MXFTOOLS_BUGREPORT "dossantos@ebu.ch"
#define MXFTOOLS_TARNAME "MXFTools"
#define MXFTOOLS_URL "http://github.com/ebu/MXFTools"

#define MXFTOOLS_VERSION (MXFTOOLS_VERSION_MAJOR << 16 | MXFTOOLS_VERSION_MINOR << 8 | MXFTOOLS_VERSION_MICRO)

#define MXFTOOLS_LIBRARY_NAME "MXFTools"

#endif